import AppKit
import Foundation
import Observation

/// One piece of text the user copied.
nonisolated struct ClipboardItem: Hashable, Identifiable, Sendable, Codable {
    var id = UUID()
    var text: String
    var copied: Date

    /// The first line, for a row (the whole text is what gets pasted).
    var preview: String {
        let line = text.split(whereSeparator: \.isNewline).first.map(String.init) ?? text
        return line.trimmingCharacters(in: .whitespaces)
    }
}

/// What the user copied, newest first, for Siri's Clipboard (⌘4), as the system's Spotlight keeps
/// it: text only, the last `limit` copies, kept across launches.
///
/// The pasteboard has no change notification, so its change count is read once a second — one
/// integer from the pasteboard server, with a generous timer leeway so the wake-up rides along
/// with others. Nothing else runs until the count moves. Copies an app marks as concealed or
/// transient (password managers, per nspasteboard.org) are never kept.
@Observable final class ClipboardHistory {
    private(set) var items: [ClipboardItem] = []

    static let limit = 50
    /// Longer copies are kept cut to this (a row shows one line; nobody pastes a book from here).
    static let maximumLength = 20_000
    nonisolated static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType",
    ]

    @ObservationIgnored private let pasteboard: NSPasteboard
    @ObservationIgnored private let storeURL: URL?
    @ObservationIgnored private var timer: (any DispatchSourceTimer)?
    @ObservationIgnored private var lastChangeCount: Int

    init(pasteboard: NSPasteboard = .general, storeURL: URL? = ClipboardHistory.defaultStoreURL) {
        self.pasteboard = pasteboard
        self.storeURL = storeURL
        lastChangeCount = pasteboard.changeCount
        if let storeURL, let data = try? Data(contentsOf: storeURL),
           let saved = try? JSONDecoder().decode([ClipboardItem].self, from: data) {
            items = Array(saved.prefix(Self.limit))
        }
    }

    nonisolated static var defaultStoreURL: URL? {
        FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first?
            .appendingPathComponent("NotchIsland", isDirectory: true)
            .appendingPathComponent("Clipboard.json")
    }

    /// Watches the pasteboard (Settings ▸ Siri ▸ Clipboard on) or stops, keeping what it has.
    func setWatching(_ watching: Bool) {
        if watching {
            guard timer == nil else { return }
            lastChangeCount = pasteboard.changeCount
            let timer = DispatchSource.makeTimerSource(queue: .main)
            timer.schedule(deadline: .now() + 1, repeating: 1, leeway: .milliseconds(500))
            timer.setEventHandler { [weak self] in
                MainActor.assumeIsolated { self?.check() }
            }
            timer.resume()
            self.timer = timer
        } else {
            timer?.cancel()
            timer = nil
        }
    }

    /// Reads the pasteboard if it changed since the last look.
    func check() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.ignoredTypes), let text = pasteboard.string(forType: .string) else { return }
        add(text)
    }

    func add(_ text: String, at date: Date = .now) {
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        let text = String(text.prefix(Self.maximumLength))
        // The same text again moves up instead of appearing twice.
        items.removeAll { $0.text == text }
        items.insert(ClipboardItem(text: text, copied: date), at: 0)
        if items.count > Self.limit { items.removeLast(items.count - Self.limit) }
        save()
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        save()
    }

    func clear() {
        items = []
        save()
    }

    /// Puts `item` on the pasteboard (and at the top of the history) without it counting as a new
    /// copy.
    func place(_ item: ClipboardItem) {
        pasteboard.clearContents()
        pasteboard.setString(item.text, forType: .string)
        lastChangeCount = pasteboard.changeCount
        add(item.text)
    }

    private func save() {
        guard let storeURL else { return }
        let items = items
        Task.detached(priority: .utility) {
            try? FileManager.default.createDirectory(at: storeURL.deletingLastPathComponent(), withIntermediateDirectories: true)
            guard let data = try? JSONEncoder().encode(items) else { return }
            try? data.write(to: storeURL, options: [.atomic, .completeFileProtection])
        }
    }

    /// Pastes into the app that was frontmost before Siri took the keyboard: ⌘V, sent once that app
    /// is active again. Needs Accessibility (the island has it for the media keys); without it the
    /// text is only on the pasteboard, ready for the user's own ⌘V.
    nonisolated static func pasteIntoFrontApp() {
        guard AXIsProcessTrusted() else { return }
        let source = CGEventSource(stateID: .combinedSessionState)
        let v: CGKeyCode = 9
        let down = CGEvent(keyboardEventSource: source, virtualKey: v, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: v, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }
}
